//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication4
{
    using System;
    using System.Collections.Generic;
    
    public partial class cust_feedback
    {
        public int Id { get; set; }
        public int c_id { get; set; }
        public int f_id { get; set; }
        public int rating_out_of_10 { get; set; }
        public System.DateTime date { get; set; }
        public string suggeston { get; set; }
    
        public virtual customer_master customer_master { get; set; }
        public virtual menu_master menu_master { get; set; }
    }
}
