//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication4
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class RegistrationEntities2 : DbContext
    {
        public RegistrationEntities2()
            : base("name=RegistrationEntities2")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<cust_feedback> cust_feedback { get; set; }
        public virtual DbSet<customer_master> customer_master { get; set; }
        public virtual DbSet<login_master> login_master { get; set; }
        public virtual DbSet<menu_master> menu_master { get; set; }
        public virtual DbSet<order_table> order_table { get; set; }
        public virtual DbSet<reservation_table> reservation_table { get; set; }
        public virtual DbSet<User> Users { get; set; }
    }
}
