//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication4
{
    using System;
    using System.Collections.Generic;
    
    public partial class menu_master
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public menu_master()
        {
            this.cust_feedback = new HashSet<cust_feedback>();
            this.order_table = new HashSet<order_table>();
        }
    
        public int f_id { get; set; }
        public string f_name { get; set; }
        public string description { get; set; }
        public string category { get; set; }
        public string available { get; set; }
        public decimal unit_price { get; set; }
        public string days_available { get; set; }
        public string special_dish { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<cust_feedback> cust_feedback { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<order_table> order_table { get; set; }
    }
}
